# -*- coding: utf-8 -*-
"""N queen using hill climbing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZQCCazHLwN_V3qFu9dF71IVvS1ay4sSb
"""

def solve_n_queens(n):
    solutions = []
    cols = set()
    pos_diags = set()  # r + c
    neg_diags = set()  # r - c
    board = [-1] * n  # board[r] = c where queen placed in row r

    def backtrack(r):
        if r == n:
            solutions.append(board.copy())
            return
        for c in range(n):
            if c in cols or (r + c) in pos_diags or (r - c) in neg_diags:
                continue
            # place
            cols.add(c)
            pos_diags.add(r + c)
            neg_diags.add(r - c)
            board[r] = c
            backtrack(r + 1)
            # remove
            cols.remove(c)
            pos_diags.remove(r + c)
            neg_diags.remove(r - c)
            board[r] = -1

    backtrack(0)
    return solutions

def print_solutions(solutions):
    for i, sol in enumerate(solutions, 1):
        print(f"Solution {i}: {sol}")  # list of column indices (row->col)
        n = len(sol)
        for r in range(n):
            row = ['Q' if sol[r] == c else '.' for c in range(n)]
            print(' '.join(row))
        print()

# Run for N=4
if __name__ == "__main__":
    n = 4
    sols = solve_n_queens(n)
    print(f"Found {len(sols)} solutions for N={n}\n")
    print_solutions(sols)